name = "CassandraBacktest"
uuid = "a1a55c07-1351-412e-8c07-6927ef52b1ed"
authors = ["Michiel van der Meulen <michielvdmeulen@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.12"

[workspace]
projects = ["test", "docs"]
